# Generated by Django 5.1.1 on 2024-11-18 12:13

import cloudinary.models
import django.contrib.auth.validators
import django.db.models.deletion
import user.models.custom_user_model
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Obligatoire ! 150 caractères ou moins. Seuls les lettres, chiffres et @/./+/-/_.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name="Nom d'utilisateur ")),
                ('first_name', models.CharField(max_length=30, verbose_name='Nom ')),
                ('last_name', models.CharField(max_length=60, verbose_name='Prénoms ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email ')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='Téléphone ')),
                ('num_cni', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='ID de la carte ')),
                ('image_recto', cloudinary.models.CloudinaryField(max_length=255, validators=[user.models.custom_user_model.file_validation], verbose_name='image_recto')),
                ('image_verso', cloudinary.models.CloudinaryField(max_length=255, validators=[user.models.custom_user_model.file_validation], verbose_name='image_verso')),
                ('user_type', models.CharField(choices=[('LOCATAIRE', 'LOCATAIRE'), ('PROPRIETAIRE', 'PROPRIETAIRE')], default='LOCATAIRE', max_length=15, verbose_name="Type d'utilisateur ")),
                ('cards_type', models.CharField(choices=[('CNI', 'CNI'), ('PASSPORT', 'PASSPORT'), ('ATTESTATION', 'ATTESTATION'), ('AUTRE', 'AUTRE')], default='CNI', max_length=20, verbose_name='Type de carte ')),
                ('avatar', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[user.models.custom_user_model.file_validation], verbose_name='avatar')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtpTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(default='c19eb7', max_length=6)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
