# Generated by Django 5.1.1 on 2024-10-16 10:50

import django.contrib.auth.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Obligatoire ! 150 caractères ou moins. Seuls les lettres, chiffres et @/./+/-/_.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name="Nom d'utilisateur ")),
                ('first_name', models.CharField(max_length=30, verbose_name='Nom ')),
                ('last_name', models.CharField(max_length=60, verbose_name='Prénoms ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email ')),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='Téléphone ')),
                ('num_cni', models.CharField(max_length=250, unique=True, verbose_name='ID de la carte ')),
                ('image_recto', models.ImageField(blank=True, null=True, upload_to='CNI/', verbose_name='Image du recto ')),
                ('image_verso', models.ImageField(blank=True, null=True, upload_to='CNI/', verbose_name='Image du verso ')),
                ('user_type', models.CharField(choices=[('LOCATAIRE', 'LOCATAIRE'), ('PROPRIETAIRE', 'PROPRIETAIRE')], default='LOCATAIRE', max_length=15, verbose_name="Type d'utilisateur ")),
                ('cards_type', models.CharField(choices=[('CNI', 'CNI'), ('PASSPORT', 'PASSPORT'), ('ATTESTATION', 'ATTESTATION'), ('AUTRE', 'AUTRE')], default='CNI', max_length=20, verbose_name='Type de carte ')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtpTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(default='5dcc2b', max_length=6)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True)),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
