# Generated by Django 5.1.1 on 2024-11-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptokenmodel',
            name='otp_code',
            field=models.CharField(default='ffbcbd', max_length=6),
        ),
    ]
