# Generated by Django 5.1.1 on 2024-10-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customusermodel_groups_customusermodel_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptokenmodel',
            name='otp_code',
            field=models.CharField(default='6ef2f4', max_length=6),
        ),
    ]
