# Generated by Django 5.1.1 on 2024-11-23 18:46

import cloudinary.models
import user.models.custom_user_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_otptokenmodel_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='image_recto',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[user.models.custom_user_model.file_validation], verbose_name='image_recto'),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='image_verso',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[user.models.custom_user_model.file_validation], verbose_name='image_verso'),
        ),
        migrations.AlterField(
            model_name='otptokenmodel',
            name='otp_code',
            field=models.CharField(default='783c91', max_length=6),
        ),
    ]
