# Generated by Django 5.1.1 on 2024-11-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customusermodel_image_recto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptokenmodel',
            name='otp_code',
            field=models.CharField(default='cef372', max_length=6),
        ),
    ]
