# Generated by Django 5.1.1 on 2024-11-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_otptokenmodel_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptokenmodel',
            name='otp_code',
            field=models.CharField(default='10fa71', max_length=6),
        ),
    ]
