# Generated by Django 5.1.1 on 2024-12-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_customusermodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptokenmodel',
            name='otp_code',
            field=models.CharField(default='783048', max_length=6),
        ),
    ]
