# Generated by Django 5.1.1 on 2024-10-09 19:20

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Obligatoire ! 150 caractères ou moins. Seuls les lettres, chiffres et @/./+/-/_.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name="Nom d'utilisateur ")),
                ('first_name', models.CharField(max_length=30, verbose_name='Nom ')),
                ('last_name', models.CharField(max_length=60, verbose_name='Prénoms ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email ')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Téléphone ')),
                ('num_cni', models.CharField(max_length=250, unique=True, verbose_name='Numéro de la CNI ')),
                ('image_recto', models.ImageField(upload_to='CNI/', verbose_name='Image du recto ')),
                ('image_verso', models.ImageField(upload_to='CNI/', verbose_name='Image du verso ')),
                ('user_type', models.CharField(choices=[('LOCATAIRE', 'LOCATAIRE'), ('PROPRIETAIRE', 'PROPRIETAIRE')], default='LOCATAIRE', max_length=15, verbose_name="Type d'utilisateur ")),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="Date d'édition ")),
                ('status', models.BooleanField(default=True, verbose_name='Status ')),
                ('content', models.TextField(verbose_name='Description ')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
