# Generated by Django 5.1.1 on 2024-10-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_customusermodel_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptokenmodel',
            name='otp_code',
            field=models.CharField(default='258950', max_length=6),
        ),
    ]
