# Generated by Django 5.1.1 on 2024-10-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_otptokenmodel_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptokenmodel',
            name='otp_code',
            field=models.CharField(default='b390c9', max_length=6),
        ),
    ]
