# Generated by Django 5.1.1 on 2024-10-13 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_otptokenmodel_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otptokenmodel',
            name='otp_code',
            field=models.CharField(default='80d199', max_length=6),
        ),
    ]
