# Generated by Django 5.1.1 on 2024-10-12 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_otptokenmodel_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='cards_type',
            field=models.CharField(choices=[('CNI', 'CNI'), ('PASSPORT', 'PASSPORT'), ('ATTESTATION', 'ATTESTATION'), ('AUTRE', 'AUTRE')], default='CNI', max_length=20, verbose_name='Type de carte '),
        ),
        migrations.AlterField(
            model_name='otptokenmodel',
            name='otp_code',
            field=models.CharField(default='a243c2', max_length=6),
        ),
    ]
