# Generated by Django 5.1.1 on 2024-10-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_otptokenmodel_otp_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='image_recto',
            field=models.ImageField(blank=True, null=True, upload_to='CNI/', verbose_name='Image du recto '),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='image_verso',
            field=models.ImageField(blank=True, null=True, upload_to='CNI/', verbose_name='Image du verso '),
        ),
        migrations.AlterField(
            model_name='otptokenmodel',
            name='otp_code',
            field=models.CharField(default='c0417f', max_length=6),
        ),
    ]
