# Generated by Django 5.1.1 on 2024-10-07 10:24

import django.contrib.auth.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="Date d'édition ")),
                ('status', models.BooleanField(default=True, verbose_name='Status ')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Requied. 150 caractères ou moins. Seuls les lettres, chiffres et @/./+/-/_.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name="Nom d'utilisateur ")),
                ('first_name', models.CharField(max_length=30, verbose_name='Nom ')),
                ('last_name', models.CharField(max_length=60, verbose_name='Prénoms ')),
                ('account_type_enum', models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium')], default='Standard', max_length=10, verbose_name='Type de compte')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Téléphone ')),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=128, verbose_name='Mot de passe ')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion ')),
            ],
            options={
                'verbose_name': 'Propriétaire',
                'verbose_name_plural': 'Propriétaires',
            },
        ),
        migrations.CreateModel(
            name='FolderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="Date d'édition ")),
                ('status', models.BooleanField(default=True, verbose_name='Status ')),
                ('acd_number', models.CharField(max_length=30, verbose_name="Numéro de l'ACD ")),
                ('property_type', models.CharField(max_length=30, verbose_name='Type de propriété ')),
                ('localization', models.CharField(max_length=30, verbose_name='Localisation ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_owner_id', to='owner.ownermodel')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
            },
        ),
    ]
