# Generated by Django 5.1.1 on 2024-10-07 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="Date d'édition ")),
                ('status', models.BooleanField(default=True, verbose_name='Status ')),
                ('label', models.TextField(verbose_name='Commentaire ')),
                ('price', models.IntegerField(verbose_name='Prix ')),
                ('address', models.IntegerField(verbose_name='Localisation ')),
                ('surface', models.IntegerField(verbose_name='Surface ')),
                ('property_type', models.IntegerField(verbose_name='Type de propriété ')),
                ('description', models.IntegerField(verbose_name='Description ')),
                ('available', models.IntegerField(verbose_name='Disponibilité ')),
                ('bedrooms_number', models.IntegerField(verbose_name='Nombre de chambres ')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_owner_id', to='owner.ownermodel')),
            ],
            options={
                'verbose_name': 'Propriété',
                'verbose_name_plural': 'Propriétés',
            },
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="Date d'édition ")),
                ('status', models.BooleanField(default=True, verbose_name='Status ')),
                ('content', models.TextField(verbose_name='Commentaire ')),
                ('note', models.IntegerField(verbose_name='Note ')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_property_id', to='property.propertymodel')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicPropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="Date d'édition ")),
                ('status', models.BooleanField(default=True, verbose_name='Status ')),
                ('swimming_pool', models.BooleanField(verbose_name='Commentaire ')),
                ('green_space', models.BooleanField(verbose_name='Espace vert ')),
                ('air_conditioning', models.BooleanField(verbose_name='Climatisation ')),
                ('nearby_school_or_university', models.BooleanField(verbose_name='A proximité Ecole/Université ')),
                ('commercial_area', models.BooleanField(verbose_name='En zone commerciale ')),
                ('garden', models.BooleanField(verbose_name='Jardin ')),
                ('quiet_area', models.BooleanField(verbose_name='Quartier calme ')),
                ('balcony_terrace', models.BooleanField(verbose_name='Balcon / Terrasse ')),
                ('gym_room', models.BooleanField(verbose_name='Salle de sport ')),
                ('furnished', models.BooleanField(verbose_name='Meublé ')),
                ('furnished_kitchen', models.BooleanField(verbose_name='Cuisine Meublée ')),
                ('city_center', models.BooleanField(verbose_name='En centre-ville ')),
                ('general_condition_new', models.BooleanField(verbose_name='Etat général: Neuf ')),
                ('guardian', models.BooleanField(verbose_name='Gardien ')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_property_id', to='property.propertymodel')),
            ],
            options={
                'verbose_name': 'Caractéristique',
                'verbose_name_plural': 'Caractéristiques',
            },
        ),
        migrations.CreateModel(
            name='VisitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création ')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="Date d'édition ")),
                ('status', models.BooleanField(default=True, verbose_name='Status ')),
                ('visit_date', models.DateField(verbose_name='Date de visite ')),
                ('comment', models.TextField(verbose_name='Commentaire ')),
                ('property', models.ManyToManyField(related_name='visit_property_id', to='property.propertymodel')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.tenantmodel')),
            ],
            options={
                'verbose_name': 'Locataire',
                'verbose_name_plural': 'Locataires',
            },
        ),
    ]
