# Generated by Django 5.1.1 on 2024-11-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='state',
            field=models.CharField(choices=[('Maintenance', 'Maintenance'), ('Disponible', 'Disponible'), ('Occupée', 'Occupée')], default='Disponible', max_length=13, verbose_name='Status '),
        ),
    ]
