# Generated by Django 5.1.1 on 2024-10-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertymodel',
            name='video_url',
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='image_url',
            field=models.JSONField(blank=True, null=True, verbose_name='Lien de la vidéo '),
        ),
        migrations.AddField(
            model_name='propertymodel',
            name='link_3d',
            field=models.JSONField(blank=True, null=True, verbose_name='Lien de la vidéo '),
        ),
    ]
