# Generated by Django 5.1.1 on 2024-10-11 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandmodel',
            name='demand_status',
            field=models.BooleanField(default=False, verbose_name='Status de la demande '),
        ),
        migrations.AddField(
            model_name='demandmodel',
            name='demand_type',
            field=models.CharField(choices=[('LOCATION', 'LOCATION'), ('VISITE', 'VISITE')], default='VISITE', max_length=15, verbose_name='Type de visite '),
        ),
        migrations.AlterField(
            model_name='propertymodel',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Lien de la vidéo '),
        ),
    ]
