# Generated by Django 5.1.1 on 2024-10-11 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_demandmodel_demand_status_demandmodel_demand_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandmodel',
            name='property',
        ),
        migrations.AddField(
            model_name='demandmodel',
            name='property',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='visit_property_id', to='property.propertymodel'),
            preserve_default=False,
        ),
    ]
