# Generated by Django 5.1.1 on 2024-11-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_propertymodel_slug_propertymodel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertymodel',
            name='city',
            field=models.CharField(default='Abidjan', max_length=50, verbose_name='Ville '),
            preserve_default=False,
        ),
    ]
