# Generated by Django 5.1.1 on 2024-11-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_propertymodel_city'),
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandmodel',
            name='demand_status',
            field=models.CharField(choices=[('EN_ATTENTE', 'EN_ATTENTE'), ('ACCEPTER', 'ACCEPTER'), ('REFUSER', 'REFUSER')], default='EN_ATTENTE', max_length=15, verbose_name='Status de la demande '),
        ),
        migrations.AddIndex(
            model_name='demandmodel',
            index=models.Index(fields=['demand_status'], name='property_de_demand__f90ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='demandmodel',
            index=models.Index(fields=['demand_type'], name='property_de_demand__709137_idx'),
        ),
    ]
